"""Initial migration

Revision ID: cfb3d60664d0
Revises: 
Create Date: 2025-08-30 22:02:49.803114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb3d60664d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact_info', sa.Text(), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('features', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('bedrooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bathrooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('images', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('floor_plan', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('amenities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('unit_metadata', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_column('unit_metadata')
        batch_op.drop_column('amenities')
        batch_op.drop_column('floor_plan')
        batch_op.drop_column('images')
        batch_op.drop_column('bathrooms')
        batch_op.drop_column('bedrooms')
        batch_op.drop_column('title')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('order')
        batch_op.drop_column('status')
        batch_op.drop_column('features')
        batch_op.drop_column('images')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('contact_info')
        batch_op.drop_column('description')
        batch_op.drop_column('logo')

    # ### end Alembic commands ###
